# Platform compliance rules for HackerOne, Bugcrowd, Intigriti

# These lists are only filled if specific programs or assets need to be excluded.

blacklist_ips: []

blacklist_domains: []

rate_limit_per_site: 30  # requests per minute

allowed_hours_utc:
  start: "00:00"
  end: "23:59"
