# Scanner configuration

nmap:
  top_ports: 100
  timeout: 300
  arguments: "-sS -T4"

shodan:
  api_key: "SHODAN_API_KEY"  # Your valid Shodan API key
  max_results: 50

output_file: "data/processed/findings.json"
